package com.ingramcontent.consolidated.labels.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BarcodeActionSignal implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public BarcodeActionSignal() {
    }




}