package com.ingramcontent.consolidated.labels.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Item implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String statusID;

	public Item() {
	}

	public java.lang.String getStatusID() {
		return this.statusID;
	}

	public void setStatusID(java.lang.String statusID) {
		this.statusID = statusID;
	}

	public Item(java.lang.String statusID) {
		this.statusID = statusID;
	}

}