package com.ingramcontent.consolidated.labels.handler;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ExecuteSqlWorkItemHandler implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ExecuteSqlWorkItemHandler() {
    }




}