package com.ingramcontent.consolidated.labels.helper;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ToteInformationHelper implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ToteInformationHelper() {
    }

    
}