package com.ingramcontent.consolidated.labels;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class handler implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public handler() {
    }




}